/**
 * `Model.init` for a converted model (P9-10, MEMORY/specs/P9-10-model-typing-pattern.md
 * items 1–2, as amended by ADR-087 Amendment 7).
 *
 * A model file declares its instance type as a module-level interface
 * (`interface Device extends Model<InferAttributes<Device>, …> { …fields… }`) and
 * its statics as another (`interface DeviceStatics { associate: … }`); both emit
 * nothing. Its factory calls
 *
 *   const Device = initModel<Device, DeviceStatics>(class extends Model {}, attributes, options);
 *
 * which does at run time exactly what `sequelize.define(name, attributes, options)`
 * did: `define` sets `options.modelName` and `options.sequelize`, then calls
 * `init` on a fresh anonymous `class extends Model {}`. The per-model definition
 * equality check (ADR-092 check (b)) holds every converted model to that.
 *
 * Why this shape and not the spec's `class X extends Model<…> { declare … }`
 * inside the factory: two models that name each other through `Models[...]`
 * (a belongsTo one way, a hasMany back) make that form fail with TS2502 — each
 * factory's return type is inferred from its class, whose base type needs the
 * other factory's return type, and so round. An instance interface at module
 * level plus an explicitly typed factory has no inference to go round.
 *
 * The typings force two things, both made here and nowhere else:
 *  - TIMESTAMPS are not passed to `init` (`attributes` omits them). Declaring
 *    `createdAt: DataTypes.DATE` to satisfy Sequelize's `init` type CHANGES the
 *    model: the attribute loses `allowNull: false` and `_autoGenerated: true`,
 *    so `sync()` creates a nullable `created_at` (spec probe 1).
 *  - The returned class is ASSERTED to be `ModelStatic<M>` with the statics `S`.
 *    That is the same claim a `declare` field makes: Sequelize's `init` defines
 *    the attribute accessors on the prototype at run time, and the statics are
 *    assigned by the factory right after this call.
 */
import type {
  Attributes,
  InitOptions,
  Model,
  ModelAttributes,
  ModelStatic,
} from "sequelize";

/** Attributes Sequelize adds itself when `timestamps` / `paranoid` are on. */
type TimestampKey = "createdAt" | "updatedAt" | "deletedAt";

/** A converted model class: instances of `M`, the statics `S`, and a prototype typed as `M`. */
export type TypedModel<
  M extends Model,
  S extends object = object,
> = ModelStatic<M> & S & { prototype: M };

/**
 * `Auto` names the timestamp attributes Sequelize adds for this model (all three by
 * default). A model that declares one of them as an ordinary column in `init` —
 * NotificationState's `deletedAt` ("hidden for this user", the model is NOT
 * paranoid) — narrows `Auto` so that column is passed to `init` as before.
 */
export function initModel<
  M extends Model,
  S extends object = object,
  Auto extends TimestampKey = TimestampKey,
>(
  model: ModelStatic<Model>,
  attributes: ModelAttributes<M, Omit<Attributes<M>, Auto>>,
  options: InitOptions<M>,
): TypedModel<M, S> {
  model.init(attributes as ModelAttributes, options as InitOptions);
  return model as TypedModel<M, S>;
}
