/**
 * Webhook request bodies (A-51).
 *
 * Mounted as `validate(schema)` from `middlewares/validation.middleware`,
 * which strips unknown keys — so a caller-supplied `tenantId` or `createdBy` is
 * removed here, before the controller sees the body.
 *
 * A caller-supplied `secret` is REFUSED (400), not stripped (P6-13). Until
 * 2026-09-27 it was stripped silently, so an integrator who sent one believed
 * they had set it and configured their receiver with a key nothing signs with.
 * The signing secret is never an input: it is generated server-side on
 * creation, on rotation and on a url change, and returned exactly once.
 *
 * The SSRF checks stay in the service (`assertSafeUrl` on write,
 * `assertResolvedHostIsPublic` before every dispatch). This schema only
 * decides the URL's shape; it does not, and cannot, decide where it resolves.
 *
 * P9-11 (ADR-093): moved to Zod. The refusal of a `secret` keeps its message.
 *
 * P9-22 (ADR-097): moved here from backend/src/validators/webhook.validator.ts,
 * which re-exports these same objects; the frontend derives its request
 * types from them. The contract for the webhook routes.
 */
import { z } from "zod";
import { booleanish, numeric, optionalText } from "./fields";

// Same ceiling as `webhooks.url` (STRING(1024)); http or https only.
const url = z
  .string()
  .trim()
  .max(1024)
  .pipe(z.url({ protocol: /^https?$/, error: "url must be an http or https URL" }));

// "*" or a dotted lowercase name such as `device.overdue`. The emitter only
// ever sends lowercase names, so an uppercase or spaced subscription would be
// stored and then never fire — a silently inert webhook. Event names are NOT
// checked against the catalogue (constants/webhookEvents, A-11): the
// frontend lets an admin type a custom one, and existing subscriptions may
// hold names from before the catalogue. A name outside it never fires.
const eventName = z
  .string()
  .trim()
  .max(100)
  .regex(/^(\*|[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*)$/, { error: "Invalid event name" });

const events = z
  .array(eventName)
  .min(1)
  .max(50)
  .refine((list) => new Set(list).size === list.length, { error: "events must not repeat a name" });

const description = optionalText(255);

// P6-13: named so the 400 says why, instead of vanishing when stripped.
const noCallerSecret = z
  .never({
    error:
      "secret is generated by the server and returned once; it cannot be supplied. " +
      "Omit it, and use POST /webhooks/:id/rotate-secret to replace one",
  })
  .optional();

// P6-13 (ADR-085): how long the replaced secret keeps signing after a
// rotation. 24 hours by default; 0 ends it at once (a suspected leak); at most
// a week, so a forgotten rotation cannot leave two live keys indefinitely.
const ROTATION_OVERLAP_DEFAULT_HOURS = 24;
const ROTATION_OVERLAP_MAX_HOURS = 168;

const createWebhookSchema = z.object({
  url,
  events,
  description,
  isActive: booleanish().optional(),
  secret: noCallerSecret,
});

// A patch must change something. A url change rotates the signing secret
// (see webhook.service#updateWebhook); the new secret is in the response.
const updateWebhookSchema = z
  .object({
    url: url.optional(),
    events: events.optional(),
    description,
    isActive: booleanish().optional(),
    secret: noCallerSecret,
  })
  .refine((v) => Object.keys(v).length >= 1, { error: "Provide at least one field to update" });

// POST /:id/rotate-secret. The body is optional; `{}` rotates with the
// default overlap.
const rotateWebhookSecretSchema = z.object({
  overlapHours: numeric(z.number().int().min(0).max(ROTATION_OVERLAP_MAX_HOURS)).default(ROTATION_OVERLAP_DEFAULT_HOURS),
  secret: noCallerSecret,
});

export {
  ROTATION_OVERLAP_DEFAULT_HOURS,
  ROTATION_OVERLAP_MAX_HOURS,
  createWebhookSchema,
  updateWebhookSchema,
  rotateWebhookSecretSchema,
};

// The client-side (input) and handler-side (output) types of each schema.
export type CreateWebhookInput = z.input<typeof createWebhookSchema>;
export type CreateWebhookBody = z.output<typeof createWebhookSchema>;
export type UpdateWebhookInput = z.input<typeof updateWebhookSchema>;
export type UpdateWebhookBody = z.output<typeof updateWebhookSchema>;
export type RotateWebhookSecretInput = z.input<typeof rotateWebhookSecretSchema>;
export type RotateWebhookSecretBody = z.output<typeof rotateWebhookSecretSchema>;
