/**
 * P9-25 (ADR-103) — the typed API client, generated from the backend's contract.
 *
 * `paths` is generated by `npm run api:types` from `backend/openapi.json`, which
 * the backend generates from the same Zod schemas its `validate()` enforces. A
 * path, parameter or body the backend does not publish is a COMPILE error here
 * — the failure mode of the hand-written services (calls to endpoints that did
 * not exist, their tests mocking the fabrication) cannot be typed.
 *
 * Transport: openapi-fetch builds and types the request; it is SENT through the
 * existing `api` methods (`./client`), so nothing about a call changes on the
 * wire or in the session — refresh-once on 401 (F-05), the password-change and
 * MFA-enrolment redirects (A-123, A-160), the access-denied store, and the
 * normalised error (F-07: a failed request REJECTS with the backend's message).
 * The call is the same `api.get(path, { params })` / `api.post(path, body)` a
 * hand-written service makes, so it is also the same seam the tests mock.
 */
import createClient, { type Middleware } from "openapi-fetch";
import { api } from "./client";
import type { components, paths } from "./generated/schema";

export type { components, paths };

/** The query object openapi-fetch was given, by the Request it built (read by the transport). */
const queries = new WeakMap<Request, Record<string, unknown>>();

/** Keep the caller's own query object: the transport hands it to axios as `params`, unserialised. */
export const keepQuery: Middleware = {
  onRequest({ request, params }) {
    if (params.query !== undefined) {
      queries.set(request, params.query as Record<string, unknown>);
    }
    return undefined;
  },
};

/** Send one built Request through `api`, and give its answer back as a JSON `Response`. */
export const apiFetch = async (request: Request): Promise<Response> => {
  const path = new URL(request.url).pathname;
  const query = queries.get(request);
  const config = query === undefined ? undefined : { params: query };
  const text = request.method === "GET" || request.method === "DELETE" ? "" : await request.text();
  const body: unknown = text === "" ? undefined : JSON.parse(text);

  let data: unknown;
  switch (request.method) {
    case "GET":
      data = config === undefined ? await api.get(path) : await api.get(path, config);
      break;
    case "DELETE":
      data = config === undefined ? await api.delete(path) : await api.delete(path, config);
      break;
    case "POST":
      data = await api.post(path, body);
      break;
    case "PUT":
      data = await api.put(path, body);
      break;
    case "PATCH":
      data = await api.patch(path, body);
      break;
    default:
      throw new Error(`Unsupported method ${request.method}`);
  }
  // `api` resolves only on 2xx (a failure has already rejected, normalised), and
  // hands back the parsed body; its exact 2xx status is not needed by any caller.
  return new Response(JSON.stringify(data ?? null), {
    status: 200,
    headers: { "content-type": "application/json" },
  });
};

/**
 * The typed client. Paths are same-origin (`/api/v1/...`), answered by the
 * Next proxy, like every other call from the browser.
 */
export const typedApi = createClient<paths>({
  // openapi-fetch needs an absolute base to build a Request; the transport
  // keeps only the path (and the query object), so the origin is never used.
  baseUrl: "http://same-origin.invalid",
  fetch: apiFetch,
});
typedApi.use(keepQuery);

/**
 * The `data` of a successful envelope, or a thrown Error when the response
 * carried none (openapi-fetch returns `{ data, error }`; failures have already
 * thrown in the transport, so a missing `data` means a 2xx without a body).
 */
export const unwrap = <T>(result: { data?: T; error?: unknown }): T => {
  if (result.data === undefined) {
    throw new Error("The API answered without a body");
  }
  return result.data;
};
