/**
 * A-51 — the webhook body schemas, exercised through the real `validate()`
 * middleware (stripUnknown, abortEarly: false), because that is the only way
 * they are ever applied.
 */
const { validate } = require("../../middlewares/validation.middleware");
const {
  createWebhookSchema,
  updateWebhookSchema,
  rotateWebhookSecretSchema,
  ROTATION_OVERLAP_DEFAULT_HOURS,
  ROTATION_OVERLAP_MAX_HOURS,
} = require("../../validators/webhook.validator");

const run = (schema, body) => {
  const req = { body };
  const res = { status: jest.fn().mockReturnThis(), json: jest.fn().mockReturnThis() };
  const next = jest.fn();
  validate(schema)(req, res, next);
  return { req, res, next, passed: next.mock.calls.length === 1 };
};

const fieldsOf = (res) => res.json.mock.calls[0][0].details.map((e) => e.field);

describe("webhook.validator — createWebhookSchema", () => {
  const valid = { url: "https://receiver.example.com/hook", events: ["device.overdue"] };

  it("accepts a minimal valid body", () => {
    const { passed, req } = run(createWebhookSchema, valid);
    expect(passed).toBe(true);
    expect(req.body).toEqual(valid);
  });

  it("P6-13: REFUSES a caller-supplied secret (400 naming it) — stripping it let an integrator believe they had set one", () => {
    const { passed, res } = run(createWebhookSchema, { ...valid, secret: "a" });
    expect(passed).toBe(false);
    expect(res.status).toHaveBeenCalledWith(400);
    expect(fieldsOf(res)).toEqual(["secret"]);
    expect(res.json.mock.calls[0][0].details[0].message).toMatch(/generated by the server/);
  });

  it("strips other unknown keys (tenantId, createdBy)", () => {
    const { req } = run(createWebhookSchema, { ...valid, tenantId: "x", createdBy: "y" });
    expect(req.body).not.toHaveProperty("tenantId");
    expect(req.body).not.toHaveProperty("createdBy");
  });

  it("accepts description, isActive and the wildcard event", () => {
    const { passed } = run(createWebhookSchema, {
      url: "http://receiver.example.com/hook",
      events: ["*", "device.calibration_due"],
      description: "ops",
      isActive: false,
    });
    expect(passed).toBe(true);
  });

  it("accepts an empty or null description", () => {
    expect(run(createWebhookSchema, { ...valid, description: "" }).passed).toBe(true);
    expect(run(createWebhookSchema, { ...valid, description: null }).passed).toBe(true);
  });

  it.each([
    ["missing url", { events: ["*"] }, "url"],
    ["non-http scheme", { url: "ftp://x.example.com", events: ["*"] }, "url"],
    ["not a uri", { url: "receiver", events: ["*"] }, "url"],
    ["over-long url", { url: `https://x.example.com/${"a".repeat(1100)}`, events: ["*"] }, "url"],
    ["missing events", { url: "https://x.example.com" }, "events"],
    ["empty events", { url: "https://x.example.com", events: [] }, "events"],
    ["events not an array", { url: "https://x.example.com", events: "device.overdue" }, "events"],
    // P9-11: The old validator reported the repeated item ("events.1"); the Zod refine reports the list.
    ["duplicate events", { url: "https://x.example.com", events: ["*", "*"] }, "events"],
    ["malformed event name", { url: "https://x.example.com", events: ["Device Overdue"] }, "events.0"],
    ["isActive not boolean", { ...valid, isActive: "yes please" }, "isActive"],
    ["over-long description", { ...valid, description: "d".repeat(256) }, "description"],
  ])("rejects %s with a 400 naming the field", (_label, body, field) => {
    const { passed, res } = run(createWebhookSchema, body);
    expect(passed).toBe(false);
    expect(res.status).toHaveBeenCalledWith(400);
    expect(fieldsOf(res)).toContain(field);
  });

  it("names the repetition, and treats names equal after trimming as repeats", () => {
    const { res } = run(createWebhookSchema, { url: "https://x.example.com", events: ["a", " a "] });
    expect(res.json.mock.calls[0][0].details).toEqual([
      { field: "events", message: "events must not repeat a name" },
    ]);
  });

  it("gives the schemas' own messages for a bad url and a bad event name", () => {
    const { res } = run(createWebhookSchema, { url: "ftp://x.example.com", events: ["Device Overdue"] });
    expect(res.json.mock.calls[0][0].details).toEqual([
      { field: "url", message: "url must be an http or https URL" },
      { field: "events.0", message: "Invalid event name" },
    ]);
  });

  it("trims the url and event names, and converts a boolean string", () => {
    const { passed, req } = run(createWebhookSchema, {
      url: "  https://x.example.com/hook  ",
      events: [" device.overdue "],
      isActive: "false",
    });
    expect(passed).toBe(true);
    expect(req.body).toEqual({ url: "https://x.example.com/hook", events: ["device.overdue"], isActive: false });
  });

  it("rejects more than 50 events", () => {
    const events = Array.from({ length: 51 }, (_v, i) => `e${String.fromCharCode(97 + (i % 26))}.n${i}`);
    const { passed, res } = run(createWebhookSchema, { url: "https://x.example.com", events });
    expect(passed).toBe(false);
    expect(fieldsOf(res)).toEqual(["events"]);
  });

  it("rejects a bodyless request as a 400, not a 500", () => {
    const { passed, res } = run(createWebhookSchema, undefined);
    expect(passed).toBe(false);
    expect(res.status).toHaveBeenCalledWith(400);
  });
});

describe("webhook.validator — updateWebhookSchema", () => {
  it("accepts a partial patch", () => {
    expect(run(updateWebhookSchema, { isActive: false }).passed).toBe(true);
    expect(run(updateWebhookSchema, { url: "https://new.example.com/hook" }).passed).toBe(true);
  });

  it("P6-13: REFUSES a caller-supplied secret alongside a real change", () => {
    const { passed, res } = run(updateWebhookSchema, { description: "x", secret: "a" });
    expect(passed).toBe(false);
    expect(fieldsOf(res)).toEqual(["secret"]);
  });

  it("rejects an empty patch", () => {
    const { passed, res } = run(updateWebhookSchema, {});
    expect(passed).toBe(false);
    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json.mock.calls[0][0].details).toEqual([
      { field: "", message: "Provide at least one field to update" },
    ]);
  });

  it("rejects a patch whose only keys are stripped unknowns", () => {
    expect(run(updateWebhookSchema, { tenantId: "x" }).passed).toBe(false);
  });

  it("rejects a patch that is only a secret", () => {
    expect(run(updateWebhookSchema, { secret: "a" }).passed).toBe(false);
  });

  it("rejects an empty events array and a bad url", () => {
    expect(run(updateWebhookSchema, { events: [] }).passed).toBe(false);
    expect(run(updateWebhookSchema, { url: "javascript:alert(1)" }).passed).toBe(false);
  });
});

describe("P6-13 — rotateWebhookSecretSchema", () => {
  it("defaults the overlap to 24 hours for a bodyless rotation", () => {
    const { passed, req } = run(rotateWebhookSecretSchema, undefined);
    expect(passed).toBe(true);
    expect(req.body).toEqual({ overlapHours: ROTATION_OVERLAP_DEFAULT_HOURS });
    expect(ROTATION_OVERLAP_DEFAULT_HOURS).toBe(24);
  });

  it("converts a numeric-string overlap", () => {
    const { passed, req } = run(rotateWebhookSecretSchema, { overlapHours: "12" });
    expect(passed).toBe(true);
    expect(req.body).toEqual({ overlapHours: 12 });
  });

  it("accepts 0 (end the old secret now) up to a week", () => {
    expect(run(rotateWebhookSecretSchema, { overlapHours: 0 }).passed).toBe(true);
    expect(run(rotateWebhookSecretSchema, { overlapHours: ROTATION_OVERLAP_MAX_HOURS }).passed).toBe(true);
    expect(ROTATION_OVERLAP_MAX_HOURS).toBe(168);
  });

  it("refuses a negative, fractional or over-long overlap", () => {
    for (const overlapHours of [-1, 1.5, ROTATION_OVERLAP_MAX_HOURS + 1, "a day"]) {
      expect(run(rotateWebhookSecretSchema, { overlapHours }).passed).toBe(false);
    }
  });

  it("refuses a caller-supplied secret on rotation too", () => {
    const { passed, res } = run(rotateWebhookSecretSchema, { secret: "a" });
    expect(passed).toBe(false);
    expect(fieldsOf(res)).toEqual(["secret"]);
  });
});
