#!/usr/bin/env node
/**
 * P22-10b (P19-08 § 4; ADR-127 Am. 1 § 3) — generates `public/sw.js` from `src/field/worker/sw.ts`:
 * transpiled by the TypeScript compiler API (types erased, nothing bundled — the source imports
 * nothing), every `export` dropped (a classic worker script), and `__CF_VERSION__` replaced by the
 * first 12 hex of the source's SHA-256 (a changed worker is a new version; its caches are new).
 *
 *   node scripts/build-sw.mjs          write public/sw.js
 *   node scripts/build-sw.mjs --check  exit 1 when public/sw.js is not what the source generates
 *
 * `npm run build` runs it before `next build`; `sw.build.test.ts` runs `--check`.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const ts = require("typescript");

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, "src/field/worker/sw.ts");
const outPath = path.join(root, "public/sw.js");

const source = readFileSync(sourcePath, "utf8").replace(/\r\n/g, "\n");
if (/^\s*import\s/m.test(source)) throw new Error("sw.ts must import nothing (a classic worker script)");
const version = createHash("sha256").update(source).digest("hex").slice(0, 12);
const { outputText } = ts.transpileModule(source, {
  compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.ESNext, removeComments: false },
});
const body = outputText
  .replace(/^export \{\};?\n?/gm, "")
  .replace(/^export (const|function|async function|class) /gm, "$1 ")
  .replace(/"__CF_VERSION__"/, JSON.stringify(version));
if (/\bexport\b/.test(body.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*$/gm, ""))) throw new Error("an export survived");
const generated = `/* GENERATED by scripts/build-sw.mjs from src/field/worker/sw.ts — do not edit. Version ${version}. */\n${body}`;

if (process.argv.includes("--check")) {
  const current = existsSync(outPath) ? readFileSync(outPath, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== generated) {
    console.error("public/sw.js is stale: run `node scripts/build-sw.mjs`");
    process.exit(1);
  }
  console.log(`public/sw.js is current (version ${version})`);
} else {
  writeFileSync(outPath, generated);
  console.log(`public/sw.js written (version ${version})`);
}
