/**
 * A-293 (ADR-100) — every certificate gets its own verification token, and no
 * caller chooses it.
 *
 * The token is what the QR code carries and what unlocks the FULL public
 * verification verdict: 24 bytes from a CSPRNG, base64url (32 characters,
 * 192 bits). It is generated by the MODEL, so every creation path gets one,
 * and a value handed to create()/bulkCreate() is replaced — the create body
 * of POST /certificates cannot carry one either (the Zod schemas strip it).
 *
 * REAL Certificate model and hooks over fixtures/memoryDb.
 */
import type * as MemoryDbModule from "../fixtures/memoryDb";
import type * as ModelsModule from "../../models";

jest.mock("../../config", () => ({
  db: jest.requireActual<typeof MemoryDbModule>("../fixtures/memoryDb").memoryDb().sequelize,
}));

const mdb = jest.requireActual<typeof MemoryDbModule>("../fixtures/memoryDb").memoryDb();
const models = jest.requireActual<typeof ModelsModule>("../../models");
// eslint-disable-next-line @typescript-eslint/no-require-imports -- the validator module (export =)
const validators = require("../../validators/certificate.validator") as {
  createCertificateSchema: { parse(v: unknown): Record<string, unknown> };
  updateCertificateSchema: { parse(v: unknown): Record<string, unknown> };
};

const TENANT = "b1000000-0000-4000-8000-000000000001";
const DEVICE = "b2000000-0000-4000-8000-000000000001";
const TOKEN_SHAPE = /^[A-Za-z0-9_-]{32}$/;
const CHOSEN = "attacker-chosen-token-0000000000";

const values = (n: number, extra: Record<string, unknown> = {}): Record<string, unknown> => ({
  tenantId: TENANT,
  deviceId: DEVICE,
  certificateNumber: `CERT-20260929-A293-${String(n).padStart(4, "0")}`,
  ...extra,
});

interface CertLike {
  verificationToken: string;
}

beforeEach(() => {
  mdb.reset();
});

describe("A-293 — Certificate.verificationToken", () => {
  it("is declared NOT NULL, and its unique index is left to migration 0096", () => {
    const attr = models.Certificate.getAttributes().verificationToken;
    expect(attr).toBeDefined();
    expect(attr.allowNull).toBe(false);
    expect(attr.field).toBe("verification_token");
  });

  it("create() generates a 192-bit base64url token", async () => {
    const cert = (await models.Certificate.create(values(1) as never)) as unknown as CertLike;

    expect(cert.verificationToken).toMatch(TOKEN_SHAPE);
    expect(Buffer.from(cert.verificationToken, "base64url")).toHaveLength(24);
    expect(mdb.rows("Certificate")[0]?.["verificationToken"]).toBe(cert.verificationToken);
  });

  it("every certificate gets a different token", async () => {
    const tokens = new Set<string>();
    for (let i = 1; i <= 50; i += 1) {
      const cert = (await models.Certificate.create(values(i) as never)) as unknown as CertLike;
      tokens.add(cert.verificationToken);
    }
    expect(tokens.size).toBe(50);
  });

  it("a token passed to create() is replaced, never stored", async () => {
    const cert = (await models.Certificate.create(values(1, { verificationToken: CHOSEN }) as never)) as unknown as CertLike;

    expect(cert.verificationToken).not.toBe(CHOSEN);
    expect(cert.verificationToken).toMatch(TOKEN_SHAPE);
    expect(mdb.rows("Certificate")[0]?.["verificationToken"]).not.toBe(CHOSEN);
  });

  it("bulkCreate() generates one per row and replaces a passed one", async () => {
    await models.Certificate.bulkCreate([values(1, { verificationToken: CHOSEN }), values(2)] as never[]);

    const tokens = mdb.rows("Certificate").map((r) => r["verificationToken"]);
    expect(tokens).toHaveLength(2);
    for (const token of tokens) {
      expect(token).toMatch(TOKEN_SHAPE);
      expect(token).not.toBe(CHOSEN);
    }
    expect(tokens[0]).not.toBe(tokens[1]);
  });

  it("the create and update schemas strip a verificationToken from a request body", () => {
    const created = validators.createCertificateSchema.parse({ deviceId: DEVICE, verificationToken: CHOSEN });
    const updated = validators.updateCertificateSchema.parse({ summary: "x", verificationToken: CHOSEN });

    expect(created).not.toHaveProperty("verificationToken");
    expect(updated).not.toHaveProperty("verificationToken");
  });
});
